In [1]:
import numpy as np

arr1 = np.arange(1, 11)
arr1

arr2 = np.random.randint(1, 10, size=(3, 3))
arr2


array([[4, 7, 2],
       [4, 6, 8],
       [5, 7, 6]])

In [2]:
arr1.sum()
arr1.mean()
arr1.max()

arr1 * 2

arr1_modified = arr1.copy()
arr1_modified[arr1_modified > 5] = 0
arr1_modified


array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0])

In [3]:
!python3 -m pip install pandas matplotlib


  Using cached pillow-12.1.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (8.8 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 6.6 MB/s  0:00:01 eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 7.7 MB/s  0:00:01m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 7.5 MB/s  0:00:00 eta 0:00:01
Using cached pillow-12.1.0-cp314-cp314-macosx_11_0_arm64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [matplotlib]8 [matplotlib]


In [4]:
import pandas as pd
import matplotlib.pyplot as plt


In [5]:
import numpy as np

arr1 = np.arange(1, 11)
arr2 = np.random.randint(1, 10, size=(3, 3))

arr1.sum()
arr1.mean()
arr1.max()

arr1 * 2

arr1[arr1 > 5] = 0
arr1


array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0])